version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-weather-app
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-weather-app
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  test_and_report:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-weather-app
    steps:
      - attach_workspace:
          at: ~/react-weather-app
      - run: yarn install
      - run: CI=true yarn start validate.withCoverage
      - run: yarn start reportCoverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-weather-app
    steps:
      - attach_workspace:
          at: ~/react-weather-app
      - run: yarn install
      - run:
          name: yarn build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CI=true PUBLIC_URL=https://the-rising-sun.now.sh yarn build
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              CI=true PUBLIC_URL=https://the-rising-sun-beta.now.sh yarn build
            else
              echo "This failed miserably!"
            fi
      - persist_to_workspace:
          root: .
          paths: .
  deployment:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/react-weather-app
    steps:
      - attach_workspace:
          at: ~/react-weather-app
      - run: yarn install
      - run: sudo yarn global add now
      - deploy:
          name: Deploy & Alias.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              now build -t ${NOW_TOKEN} -n=the-rising-sun --static
              now -t ${NOW_TOKEN} alias the-rising-sun.now.sh
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              now build -t ${NOW_TOKEN} -n=the-rising-sun --static
              now -t ${NOW_TOKEN} alias the-rising-sun-beta.now.sh
            else
              echo "This failed miserably!"
            fi
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - test_and_report:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - development
                - master
      - deployment:
          requires:
            - test_and_report
            - build
          filters:
            branches:
              only:
                - development
                - master
